Vagrant.configure("2") do |config|
    config.vm.define "eventstore" do |eventstore|
		eventstore.vm.provider "virtualbox" do |v|
            v.cpus = 2
            v.memory = 8192
        end
        eventstore.vm.box = "ubuntu/trusty64"
    	eventstore.vm.network "private_network", ip: "192.168.50.11"
        eventstore.vm.network "forwarded_port", guest: 2113, host: 2113
        eventstore.vm.network "forwarded_port", guest: 1113, host: 1113
        eventstore.vm.provision :shell, :path => "./setup/eventstore/single-bootstrap.sh"
        eventstore.vm.provision :shell, :path => "./setup/eventstore/projections/install.sh"
    end

    config.vm.define "mongodb" do |mongodb|
		mongodb.vm.box = "ubuntu/trusty64"
        mongodb.vm.network "private_network", ip: "192.168.50.12"
        mongodb.vm.network "forwarded_port", guest: 27017, host: 27017
        mongodb.vm.network "forwarded_port", guest: 27018, host: 27018
        mongodb.vm.provision  :shell, :path => "./setup/mongodb/bootstrap.sh"
    end
end