Vagrant.configure("2") do |config|
  config.vm.define "agent" do |agent|
    agent.vm.box = "ubuntu/xenial64"
    agent.vm.provision "ansible_local" do |ansible|
      ansible.become = true
      ansible.playbook = "playbook.yml"
    end
  end
end
